port="8888"
dev = true


[DataBase]
dbHost="localhost"
dbPort="3306"
dbSchemaName="payment_bridge"
dbUsername="root"
dbPwd="123456"
dbArgs="charset=utf8mb4&parseTime=True&loc=Local"

[MainnetNode]
rpcHost="http://192.168.88.217"
rpcPort="8545"
